#AndroidIDE: enforce UTF-8 & locale for Gradle daemon
#Sat Nov 08 21:31:03 GMT 2025
android.nonTransitiveRClass=true
kotlin.code.style=official
systemProp.user.language=en
systemProp.user.country=US
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
# 性能和兼容性改进
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding\=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=true
org.gradle.caching=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=true
kotlin.caching.enabled=true

